server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false




security:
  jwt:
    jwk-set-uri: ${AUTH_SERVICE_JWK_URI:http://localhost:9000/oauth2/jwks}

resilience4j:
  circuitbreaker:
    instances:
      studentServiceCircuitBreaker:
        base-config: default
      notificationServiceCircuitBreaker:
        base-config: default
