server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/api/students/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
            - id: user-service
              uri: lb://auth-service
              predicates:
                - Path=/api/users/**
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,circuitbreakers,circuitbreakerevents,gateway

security:
  jwt:
    jwk-set-uri: ${AUTH_SERVICE_JWK_URI:http://localhost:9000/oauth2/jwks}

resilience4j:
  circuitbreaker:
    instances:
      studentServiceCircuitBreaker:
        base-config: default
      notificationServiceCircuitBreaker:
        base-config: default
